### ISSUE TITLE
Support for async logging

### ISSUE THREAD

**Issue by gegles** [guangie88/spdlog_setup#44]
I've looked everywhere but can't seem to find how to enable async logging via spdlog_setup.

Am I missing something? Is this planned to be supported soon?

**Comment by guangie88** [comment]
Thanks for the feedback, it's not supported at the moment.

It seems like the way it's constructed is not too different from sync, so I might take a look when I'm free and try implementing it.

**Comment by gegles** [comment]
Thanks, that would be great! That's the one thing stopping from switching to spdlog_setup... I'll see if I find time to contribute a PR, but it would probably a lot faster for you to do it if you get to it.

**Comment by gegles** [comment]
Any hope of getting this soon? Just trying to plan for our release...

**Comment by guangie88** [comment]
Hey thanks for the wait, the support for async has arrived, the example for async looks something like this:

```toml
[global_thread_pool]
queue_size = 8192
num_threads = 1

[[thread_pool]]
name = "tp"
queue_size = 4096
num_threads = 2

# Uses global thread pool
[[logger]]
type = "async"
name = "global_async"
sinks = ["console_mt"]
pattern = "succient"

[[logger]]
type = "async"
name = "local_async"
sinks = ["console_mt"]
pattern = "succient"
thread_pool = "tp"
overflow_policy = "overrun_oldest"  # block (default) | overrun_oldest
```

Will be prepping this whole thing as a proper `0.3.0` release too.
