### ISSUE TITLE
Feature request: yaml configuration file

### ISSUE THREAD

**Issue by PJ127** [guangie88/spdlog_setup#59]
Hello,

thank you for your great work. I've kept wondering why you are using .toml file, which are less common than for example .yaml file, and more tedious to read (especially when you don't have a plugin, like in Eclipse).

```toml
[[sink]]
name = "null_sink_mt"
type = "null_sink_mt"
level = "info"

# only works for Linux
[[sink]]
name = "syslog_st"
type = "syslog_sink_st"
```

whereas you could have a more elegant and less redundant:
``` yaml
sink:
    null_sink_mt: 
           type: null_sink_mt
           level: info
    syslog_st: # only work for Linux
           type: syslog_sink_st
```

Thank you for your time.
